name: Build Max+ Android

on:
  workflow_dispatch:

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build:
    runs-on: ubuntu-24.04
    timeout-minutes: 40

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache Bun
        uses: actions/cache@v4
        with:
          path: |
            ~/.bun/install/cache
          key: bun-${{ runner.os }}-${{ hashFiles('bun.lockb') }}

      - name: Cache Gradle
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}

      - name: Rust cache
        uses: swatinem/rust-cache@v2
        with:
          workspaces: src-tauri

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Setup Android NDK toolchain PATH
        run: |
          echo "$ANDROID_SDK_ROOT/ndk/27.3.13750724/toolchains/llvm/prebuilt/linux-x86_64/bin" >> $GITHUB_PATH

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: |
            aarch64-linux-android
            armv7-linux-androideabi
            x86_64-linux-android

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Install Android NDK
        run: |
          sdkmanager "ndk;27.3.13750724"

      - name: Configure Android NDK
        run: |
          export NDK=$ANDROID_SDK_ROOT/ndk/27.3.13750724

          echo "ANDROID_NDK_HOME=$NDK" >> $GITHUB_ENV
          echo "NDK_HOME=$NDK" >> $GITHUB_ENV

          echo "$NDK/toolchains/llvm/prebuilt/linux-x86_64/bin" >> $GITHUB_PATH

      - name: Configure Android environment
        run: |
          echo "ANDROID_HOME=$ANDROID_SDK_ROOT" >> $GITHUB_ENV

      - name: Generate Icons
        run: bun run tauri icon static/favicon.png

      - name: Init Tauri Android
        run: bunx tauri android init

      - name: Patch Cargo.toml for CI
        run: |
          sed -i 's|path = "../../rumax"|git = "https://github.com/me0wkie/rumax.git", branch = "main"|g' src-tauri/Cargo.toml

          echo "Cargo.toml updated:"
          grep rumax src-tauri/Cargo.toml

      - name: Decode Android keystore
        run: |
          echo "${{ secrets.ANDROID_KEYSTORE_BASE64 }}" | base64 --decode > release.jks

      - name: Build Multi Android
        env:
          ANDROID_KEYSTORE: ${{ github.workspace }}/release.jks
          ANDROID_KEY_ALIAS: ${{ secrets.ANDROID_KEY_ALIAS }}
          ANDROID_KEYSTORE_PASSWORD: ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
          ANDROID_KEY_PASSWORD: ${{ secrets.ANDROID_KEY_PASSWORD }}
        run: |
          bunx tauri android build --apk --split-per-abi

      - name: Build Universal Android
        env:
          ANDROID_KEYSTORE: ${{ github.workspace }}/release.jks
          ANDROID_KEY_ALIAS: ${{ secrets.ANDROID_KEY_ALIAS }}
          ANDROID_KEYSTORE_PASSWORD: ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
          ANDROID_KEY_PASSWORD: ${{ secrets.ANDROID_KEY_PASSWORD }}
        run: |
          bunx tauri android build --apk

      - name: Upload arm64 APK
        uses: actions/upload-artifact@v4
        with:
          name: maxplus-android-arm64
          path: |
            src-tauri/gen/android/app/build/outputs/apk/arm64/release/*.apk

      - name: Upload armeabi-v7a APK
        uses: actions/upload-artifact@v4
        with:
          name: maxplus-android-arm
          path: |
            src-tauri/gen/android/app/build/outputs/apk/arm/release/*.apk

      - name: Upload x86 APK
        uses: actions/upload-artifact@v4
        with:
          name: x86-apk
          path: |
            src-tauri/gen/android/app/build/outputs/apk/x86/release/*.apk

      - name: Upload x86_64 APK
        uses: actions/upload-artifact@v4
        with:
          name: x86_64-apk
          path: |
            src-tauri/gen/android/app/build/outputs/apk/x86_64/release/*.apk

      - name: Upload universal APK
        uses: actions/upload-artifact@v4
        with:
          name: universal-apk
          path: |
            src-tauri/gen/android/app/build/outputs/apk/universal/release/*.apk
